### ISSUE TITLE
Update request..

### ISSUE THREAD

**Issue by Nurul-GC** [FatihBozik/license-generator-intellij-plugin#10]
> Hello Great Guy, hope you're doing well..
I just would like to remind you to update the plugin please, I really need it operable..

**After I updated my PyCharm I got this notification..**

- Plugin error: Plugin 'License Generator' (version '0.0.13') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PC-212.4746.96

**Comment by FatihBozik** [comment]
Hi @Nurul-GC,

Thanks for your feedback. Fixed by [0.0.14](https://github.com/FatihBozik/license-generator-intellij-plugin/releases/tag/v0.0.14) version. The new version will be live after JetBrains approval.
