### ISSUE TITLE
0.0.14 doesnt work on IntelliJ 2021.2.1 

### ISSUE THREAD

**Issue by fahaad9** [FatihBozik/license-generator-intellij-plugin#12]
I just installed the IntelliJ 2021.2.1 on MacOS and License generator doesn't seem to work. Below is the information.

Thanks

IntelliJ IDEA 2021.2.1 (Ultimate Edition)
Build #IU-212.5080.55, built on August 23, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 1, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins: io.github.fatihbozik.intellij-license-generator (0.0.14), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7)
Kotlin: 212-1.5.30-release-409-IJ4638.7

**Comment by FatihBozik** [comment]
Hi @fahaad9, 0.0.15 version works fine with 2021.2.1 version.
