### ISSUE TITLE
Request to an update!

### ISSUE THREAD

**Issue by Nurul-GC** [FatihBozik/license-generator-intellij-plugin#13]
Hello great @FatihBozik, hope you're doing fine!
I just would like to ask if you can release a new version please, I can't use the plugin, at all..

**IDE Exception:**

```txt
Plugin 'License Generator' (version '0.0.14') is not compatible with the current version of the IDE, 
because it requires build 212.* or older but the current build is IC-213.5744.223
```

**Comment by FatihBozik** [comment]
Hi @Nurul-GC, thanks for your feedback. Compatible version: [0.0.15](https://plugins.jetbrains.com/plugin/13307-license-generator/) is available now.
