### ISSUE TITLE
Supports GoLand 2022.1.1

### ISSUE THREAD

**Issue by lkqm** [FatihBozik/license-generator-intellij-plugin#15]
In jetbarins marketplace it's tips that: Not compatible with the version of your running IDE (GoLand 2022.1.1)

**Comment by FatihBozik** [comment]
Thank you. Fixed by 0.0.16 version. The new version will be live after JetBrains approval. If you don't want to wait, you can manually download latest version from the [link](https://github.com/FatihBozik/license-generator-intellij-plugin/releases/tag/v0.0.16).
